### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by MrBoolean** [MrBoolean/gulp-run#41]
I am not sure if u are still looking for a new maintainer... In case your **deprecation warning** is still up-to-date - i am able to handle it... 
contact me on a free minute.

**Comment by nascosto** [comment]
:+1:

**Comment by johngerome** [comment]
:+1:

**Comment by cbarrick** [comment]
@MrBoolean has agreed to take over the repository, and we are working to get ownership transferred.
