### ISSUE TITLE
Confused: cbarrick's version vs. this?

### ISSUE THREAD

**Issue by hildjj** [MrBoolean/gulp-run#42]
`npm install gulp-run` gets cbarrick's deprecated version, but `npm home gulp-run` comes here.  If you've taken over, can you publish a new version to true things up?

**Comment by hildjj** [comment]
The reason this is an issue is that gulp prints `Warning: gulp-run is deprecated` on every run, which is causing people to file bugs on *my* project.

**Comment by MrBoolean** [comment]
Just a warning. Currently, the next version is not ready for production. So you need to wait a few days.

**Comment by nfantone** [comment]
So... have "a few days" passed already? Any help still needed?

**Comment by MrBoolean** [comment]
Done.
